# apps/cms/netlify.toml

[build]
  # set the repo root as the base folder so that `npm install` runs in that context
  # we want npm v7 workspaces install behavior and this would theoretically do that
  base = "../../"
  # since the base folder is the root of the repo, we first need to change back down into `apps/cms` before building the app
  command = "cd packages/client/ && npm run build"
  # since the www and cms apps are independent of one another, we don’t need to build the cms app just because some stuff changed in `apps/www`
  # if _only_ something inside apps/www changed, we skip the build! wowzers!
  # if there are changes elsewhere (e.g. in the cms package, or in a shared package) the build runs per usual
  # the following git diff asks, “what changed in this latest commit, ignoring the apps/www folder”